services:
  node:
    image: node:16.14
    volumes:
      - ./application:/application
    working_dir: /application

  database:
    image: postgres
    env_file:
      - docker/env/project.env
    ports:
      - "5432:5432"

  php-fpm:
    build: docker/dockerfile/php-fpm
    env_file:
      - docker/env/project.env
    volumes:
      - ./application:/application
    working_dir: /application
    ports:
      - "80:8000"
    depends_on:
      - database
    command: symfony serve --no-tls